# Generated by Django 5.2.13 on 2026-04-23 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('spi', 'API Fetch')], max_length=10)),
                ('records_loaded', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=10)),
                ('rated', models.CharField(blank=True, default='', max_length=20)),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('director', models.CharField(blank=True, default='', max_length=200)),
                ('plot', models.TextField(blank=True, default='')),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('api', 'API Fetch')], default='api', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imdb_rating'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(help_text='Spotify tracj ID', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('artists', models.CharField(max_length=300)),
                ('album_name', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(help_text='Spotify popularity score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration_ms', models.IntegerField(help_text='Track duration in milliseconds')),
                ('explicit', models.BooleanField(default=False)),
                ('danceability', models.FloatField(help_text='0.0 to 1.0')),
                ('energy', models.FloatField(help_text='0.0 to 1.0')),
                ('loudness', models.FloatField(help_text='Decibals, typically -60 to 0')),
                ('liveness', models.FloatField(help_text='0.0 to 1.0')),
                ('valence', models.FloatField(help_text='0.0 to 1.0, musical positiveness')),
                ('temp', models.FloatField(help_text='BPM')),
                ('popularity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('energy_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.genre')),
            ],
            options={
                'ordering': ['-popularity'],
                'unique_together': {('track_id', 'genre')},
            },
        ),
    ]
