# Generated by Django 5.2.13 on 2026-04-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='temp',
            new_name='tempo',
        ),
    ]
